
//@version=4
study("MACD Breakout", overlay=1)

//***************  MACD ***************//
// {

/// INPUTS
// {
htfRes = input("60", " MACD TimeFrame", input.resolution, group="MACD SETTINGS")
macdflen = input(8, "MACD Fast MA", input.integer, group="MACD SETTINGS")
macdslen = input(17, "macd Slow MA", input.integer, group="MACD SETTINGS")
siglen = input(9, "MACD signal Line", input.integer, group="MACD SETTINGS")
gaps = input(true, "Gaps")
//}

// FUNCTIONS
// {
_macd() =>
    macdSrc     = close
    FastMa = ema(macdSrc, macdflen)
    SlowMa = ema(macdSrc, macdslen)
    macd    = FastMa - SlowMa
    macd
    
_signal() =>
    // Calculating
    macdSrc     = close
    FastMa = ema(macdSrc, macdflen)
    SlowMa = ema(macdSrc, macdslen)
    macd    = FastMa - SlowMa
    signal  = ema(macd, siglen)
    signal 

_color() =>
    // Calculating
    macdSrc     = close
    FastMa = ema(macdSrc, macdflen)
    SlowMa = ema(macdSrc, macdslen)
    macd    = FastMa - SlowMa
    signal  = ema(macd, siglen)
    hist    = macd - signal
    (hist>=0 ? (hist[1] < hist ? #26A69A : #B2DFDB) : (hist[1] < hist ? #FFCDD2 : #EF5350) )

htf(_res, _exp, gaps_on)  => gaps_on == 0 ? security(syminfo.tickerid, _res, _exp) :
  gaps_on == true ? security(syminfo.tickerid, _res, _exp, barmerge.gaps_on, barmerge.lookahead_off ) : 
  security(syminfo.tickerid, _res, _exp, barmerge.gaps_off, barmerge.lookahead_off )

//}

// CALCULATION
// {
macd   = htf(htfRes, _macd(), gaps)
signal = htf(htfRes, _signal(), gaps)
mcolor = htf(htfRes, _color(), gaps)

// Calculate hist 
hist    = htf(htfRes, macd - signal, 0)
//}
//}

//*************** S/R ZONES ***************//
// {

// FILTER FOR ZONE SELECTION
//{
useFilt = input(true, "Use Filter", group="FILTER")
rsiRes = input("", "RSI Timeframe", input.resolution, group="FILTER")
rsiLen = input(14, "RSI Length", input.integer, group="FILTER")
rsiOb = input(65, "RSI Overbought", group="FILTER")
rsiOs = input(35, "RSI Oversold", group="FILTER")

htfRsi = htf(rsiRes, rsi(close, rsiLen), gaps)

isRsiOb = htfRsi >= rsiOb
isRsiOs = htfRsi <= rsiOs

//}

// ZONES
// {

//MACD HIST PIVOT POINT
histIncBelow = htf(htfRes, rising(hist, 1), 0) and hist < 0
histDecAbove = htf(htfRes, falling(hist, 1), 0) and hist > 0

startIncBelow = useFilt ? htf(htfRes, histIncBelow[1] == false and histIncBelow == true, 0) and isRsiOs : 
  htf(htfRes, histIncBelow[1] == false and histIncBelow == true, 0)
  
startDecAbove = useFilt ? htf(htfRes, histDecAbove[1] == false and histDecAbove == true, 0) and isRsiOb : 
  htf(htfRes, histDecAbove[1] == false and histDecAbove == true, 0) 

//To Mark out zone, mark the highs and the lows of the htf candles
htfbarHigh = htf(htfRes, high, 0)
htfbarLow = htf(htfRes, low, 0)

longZnHigh = startIncBelow ? htfbarHigh : na
longZnLow = startIncBelow ? htfbarLow : na

var longTop = 0.0
var longBott = 0.0

if (startIncBelow)
    longTop := longZnHigh
    longBott := longZnLow
    
shortZnHigh = startDecAbove ? htfbarHigh : na
shortZnLow = startDecAbove ?  htfbarLow : na

var shortTop = 0.0
var shortBott = 0.0

if (startDecAbove)
    shortTop := shortZnHigh
    shortBott := shortZnLow

//}

//}

//*************** STRATEGY EXECUTIONS ***************//
// {

//FUNCTION
InZone(_top, _bott, _index) => _index == 0 ? (high <= _top and high >= _bott ) or 
  ( low <= _top and low >= _bott) or (high >= _top and low <= _bott) : 
  (high[_index] <= _top and high[_index] >= _bott ) or 
  ( low[_index] <= _top and low[_index] >= _bott) or (high[_index] >= _top and low[_index] <= _bott)
 
//EXECUTION

//FOR LONGS 
prevBarInLongZn = InZone(longTop, longBott, 1)
currBarInLongZn = InZone(longTop, longBott, 0)
prevBarAboveLongZn = (not InZone(longTop, longBott, 1)) and low[1] > longTop
prevBarBelowLongZn = (not InZone(longTop, longBott, 1)) and high[1] < longBott

priceRetouchLong = prevBarAboveLongZn and  currBarInLongZn

//FOR SHORTS
prevBarInShortZn = InZone(shortTop, shortBott, 1)
currBarInShortZn = InZone(shortTop, shortBott, 0)
prevBarAboveShortZn = (not InZone(shortTop, shortBott, 1)) and low[1] > shortTop
prevBarBelowShortZn = (not InZone(shortTop, shortBott, 1)) and high[1] < shortBott

priceRetouchShort = prevBarBelowShortZn and  currBarInShortZn
//}

// PLOTS
// {

// znTop = plot(startIncBelow or startDecAbove ? znHigh : na, title='Top', color=color.blue, style=plot.style_linebr, linewidth=2)
// znBott = plot(startIncBelow or startDecAbove ? znLow : na, title='Bottom', color=color.blue, style=plot.style_linebr, linewidth=2)
// fill(znTop, znBott, startIncBelow? color.new(color.olive, 80) : color.new(color.maroon, 80))

// bgcolor(startIncBelow ? color.new(color.lime, 70) : na)
// bgcolor(startDecAbove ? color.new(color.red, 70) : na)

//PLOTS FOR LONGS
longZnTop = plot(longTop, "Long Zone Top", color.blue, linewidth=2)
longZnBott = plot(longBott, "Long Zone Bottom", color.blue, linewidth=2)
fill(longZnTop, longZnBott, color.new(color.olive, 80))

//PLOTS FOR SHORTS
shortZnTop = plot(shortTop, "Short Zone Top", color.blue, linewidth=2)
shortZnBott = plot(shortBott, "Short Zone Bottom", color.blue, linewidth=2)
fill(shortZnTop, shortZnBott, color.new(#e81c34, 80))

// plotshape(priceRetouchShort, "Long", shape.triangleup, location.belowbar, color.lime, size = size.small)
// plotshape(priceRetouchShort, "Short", shape.triangledown, location.abovebar, color.maroon, size = size.small)

//}