
//@version=4
study("MACD HIST", overlay=1)

//***************  MACD ***************//
//{

/// INPUTS
// {
htfRes = input("60", " MACD TimeFrame", input.resolution, group="MACD SETTINGS")
macdflen = input(8, "MACD Fast MA", input.integer, group="MACD SETTINGS")
macdslen = input(17, "macd Slow MA", input.integer, group="MACD SETTINGS")
siglen = input(9, "MACD signal Line", input.integer, group="MACD SETTINGS")
//}

// FUNCTIONS
// {
_macd() =>
    macdSrc     = close
    FastMa = ema(macdSrc, macdflen)
    SlowMa = ema(macdSrc, macdslen)
    macd    = FastMa - SlowMa
    macd
    
_signal() =>
    // Calculating
    macdSrc     = close
    FastMa = ema(macdSrc, macdflen)
    SlowMa = ema(macdSrc, macdslen)
    macd    = FastMa - SlowMa
    signal  = ema(macd, siglen)
    signal 

_color() =>
    // Calculating
    macdSrc     = close
    FastMa = ema(macdSrc, macdflen)
    SlowMa = ema(macdSrc, macdslen)
    macd    = FastMa - SlowMa
    signal  = ema(macd, siglen)
    hist    = macd - signal
    (hist>=0 ? (hist[1] < hist ? #26A69A : #B2DFDB) : (hist[1] < hist ? #FFCDD2 : #EF5350) )

htf(_res, _exp, gaps_on)  => gaps_on == 0 ? security(syminfo.tickerid, _res, _exp) :
  gaps_on == true ? security(syminfo.tickerid, _res, _exp, barmerge.gaps_on, barmerge.lookahead_off ) : 
  security(syminfo.tickerid, _res, _exp, barmerge.gaps_off, barmerge.lookahead_off )

//}

// CALCULATION
// {
macd   = htf(htfRes, _macd(), true)
signal = htf(htfRes, _signal(), true)
mcolor = htf(htfRes, _color(), true)

// Calculate hist 
hist    = htf(htfRes, macd - signal, 0)
//}
//}-----End of  MACD

//*************** S/R ZONES ***************//
// INPUTS
//{
usePrevZn = input(false, "Use Previous Bar as Zone")
//}

//ZONE MARKING
// {
histIncBelow = htf(htfRes, rising(hist, 1), 0) and hist < 0
histDecAbove = htf(htfRes, falling(hist, 1), 0) and hist > 0

startIncBelow = htf(htfRes, histIncBelow[1] == false and histIncBelow == true, 0)
startDecAbove = htf(htfRes, histDecAbove[1] == false and histDecAbove == true, 0)

//To Mark out zone, mark the highs and the lows of the htf candles

htfprevbarHigh = htf(htfRes, high[1], 0)
htfprevbarLow = htf(htfRes, low[1], 0)

htfbarHigh = htf(htfRes, high, 0)
htfbarLow = htf(htfRes, low, 0)

znHigh = usePrevZn ? htfprevbarHigh : htfbarHigh
znLow = usePrevZn ? htfprevbarLow : htfbarLow

//}

// PLOTS
//{
// plot(hist, style = plot.style_histogram, color=mcolor, linewidth=3)

znTop = plot(startIncBelow or startDecAbove ? znHigh : na, title='Top', color=color.blue, style=plot.style_linebr, linewidth=2)
znBott = plot(startIncBelow or startDecAbove ? znLow : na, title='Bottom', color=color.blue, style=plot.style_linebr, linewidth=2)
fill(znTop, znBott, startIncBelow ? color.new(color.olive, 80) : color.new(color.maroon, 80))

bgcolor(startIncBelow ? color.new(color.lime, 70) : na)
bgcolor(startDecAbove ? color.new(color.red, 70) : na)
//}