entry := i_entFvgInx == "Closest to Price" ? box.get_bottom( array.get(upfvgBox, array.size(upfvgBox) - 1) ) :
          i_entFvgInx == "Closest to Orderblock" ? box.get_bottom( array.get(upfvgBox, array.size(upfvgBox) - 1 - count_bearObFvg) ) : 
          i_entFvgInx == "Average of Both" ? ( ( box.get_bottom( array.get(upfvgBox, array.size(upfvgBox) - 1) ) ) + 
            ( box.get_bottom( array.get(upfvgBox, array.size(upfvgBox) - 1 - count_bearObFvg) ) ) ) / 2 : na