// SEQUENCING ALGORITHM FOR SELL/OVERBOUGHT SCEANRIOS
// {
    
var countOS = 0
var countOsZn = 0

var osDone = "none"
var osNext = "" 

if osNext == ""
    if rsiOs and countOS == 0
        countOS := 1
        osDone := "os 1"
        osNext := "lim 1"
    
else if osNext := "lim 1"
    if rsiInOsLimZn and countOsZn == 0 and osDone == "os 1"
        countOsZn := 1
        osDone := "lim 1"
        osNext := "os 2"

else if osNext := "os 2"
    if rsiInOsLimZn and countOS == 1 and osDone == "lim 1"
        countOS := 2
        osDone := "os 2"
        osNext := "lim 2"

else if osNext := "lim 2"
    if rsiInOsLimZn and countOsZn == 1 and osDone == "os 2"
        countOsZn := 2
        osDone := "lim 2"
        osNext := "os 3"
        
else if osNext := "os 3"
    if rsiInOsLimZn and countOS == 2 and osDone == "lim 2"
        countOS := 3
        osDone := "os 3"
        osNext := "lim 3"

else if osNext := "lim 3"
    if rsiInOsLimZn and countOsZn == 2 and osDone == "os 3"
        countOsZn := 3
        osDone := "lim 3"
        osNext := "os 4"
    
else if osNext := "os 4"
    if rsiInOsLimZn and countOS == 3 and osDone == "lim 3"
        countOS := 4
        osDone := "os 4"
        osNext := "lim 4"

else if osNext := "lim 4"
    if rsiInOsLimZn and countOsZn == 3 and osDone == "os 4"
        countOsZn := 4
        osDone := "lim 4"

// }
